### PR TITLE
feat(v3) add support for oas v3 securitySchemes and multiple server urls

### PR DESCRIPTION
**Pull request by nateslo**
Adds support for oas v3 securitySchemes and multiple server urls

### CODE REVIEW

**Comment by darrenjennings** [comment]
This repo has unit tests btw, would recommend adding tests for new features.

**Comment by levfishbluefish** [comment]
Do you have a test spec with the security schemes we can check against?

**Review by levfishbluefish — CHANGES_REQUESTED** [review]
We need to update this so that when someone changes the server url from the drop-down it will re-render the code snippets to use the new URL

**Comment by levfishbluefish** [comment]
Video of the above mentioned functionality needed: https://cl.ly/95e4ca2f9a49

**Review by Jlawlzz — APPROVED** [review]
Tested dropdown functionality, looks like it is up and running! 🌮

**Comment by nateslo** [comment]
@levfishdevfish The drop down is functioning when used with the updated version of swaggerUI

**Pull request merged**
